"""
Created on Sun Feb 16 01:35:00 2020

@description Read Google sheet data & write in Trello
@author Richard
"""
#%%
import os;
import json
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import requests

# Load local key and data
root_dir = os.path.abspath(os.path.dirname(__file__));
key_dir = root_dir + "/../mykey/Trello_Key.json";

with open(key_dir,"r") as load_f:
    data = json.load(load_f);

info = data["OKR_EXCEL"]
header = info["HEADER"]
trelloData = data["20_CO_SPRINT_TRELLO"]

#%%
# Setting Google API info and call Google Sheet API
# Need to do "pip install --upgrade google-api-python-client oauth2client gspread" in env
# Need to set service account in Google API console
# Then share sheet to this service account.
# reference: https://missterhao.me/2019/01/05/python-google-sheet-crud2/ 
GServiceKey_dir = root_dir + "/../myKey/googleAPIKey.json";
scope = ["https://spreadsheets.google.com/feeds",'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name(GServiceKey_dir, scope)
client = gspread.authorize(creds)

spreadSheet = client.open(info["NAME"]);
sheet = spreadSheet.worksheet(info["SHEET1"])

for rows in sheet.get_all_records():
    print(f"{rows[header['COL_C']]}")
    print(f"{rows[header['COL_D']]}")
    break;

#%%

board_id = trelloData["BOARD_ID"]
API_LIST_CARD = "https://api.trello.com/1/boards/{}/cards".format(board_id)

queryString = {
    "key": trelloData["API_KEY"],
    "token": trelloData["ACCESS_TOKEN"]
}

response = requests.get(API_LIST_CARD,params=queryString)
responseJSON = response.json()

responseJSON

#%%
API_LIST_LABEL = "https://api.trello.com/1/boards/{}/labels".format(board_id)
queryString = {
    "fields":"all",
    "key": trelloData["API_KEY"],
    "token": trelloData["ACCESS_TOKEN"]
}

response = requests.get(API_LIST_LABEL,params=queryString)
responseJSON = response.json()
for item in responseJSON:
    print("===")
    print(item)

#%%
# access token is generated by this url
# https://trello.com/1/connect?key=yourkey&expiration=never&response_type=token&scope=read,write

API_CREATE_CARD = "https://api.trello.com/1/cards"
queryString = {
    "idList": trelloData["LIST"]["TASK"],
    "key": trelloData["API_KEY"],
    "token": trelloData["ACCESS_TOKEN"],
    "name": "測試",
    "idMembers": trelloData["MY_TAG_ID"],
    # "idLabels": [""],
    "desc": "這是描述"
}

response = requests.post(API_CREATE_CARD,params=queryString)

print(response.text)


#%%